# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='pastor',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goat',
            name='profile_pic',
            field=models.ImageField(default='None', upload_to=''),
            preserve_default=False,
        ),
    ]
